### ISSUE TITLE
Build error with raspberry pi3 kernel

### ISSUE THREAD

**Issue by titusece** [rellimmot/Sony-IMX219-Raspberry-Pi-V2-CMOS#1]
Hello,
I am interested in this driver and want to insert it in raspberry pi board.
So I tried to build this driver as module and getting build error, can you please help me on this ?

Getting file not found error for the following include files ? where can I get that ?
#include <linux/xlog.h>
#include "kd_camera_hw.h"
#include "kd_imgsensor.h"
#include "kd_imgsensor_define.h"
#include "kd_imgsensor_errcode.h"

I just googled and found this driver seems like used for mediatek processor ?
Can I indeed use it for raspberry pi3 board with pi camera v2 ?

Thanks for the help.

Regards,
Titus S.

**Comment by VT-Github-Raspberrypi** [comment]
Even i am also getting same build error .
Can somebody help us ?.
